language: objective-c
osx_image: xcode8.3

cache:
  directories:
  - Carthage

before_install: true
install:
  - rvm get stable || true
  - brew update || true
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --no-use-binaries --cache-builds || true
before_script:
 - chmod +x ./script/build
script:
  - script/build
xcode_project: FeathersSwiftSocketIO.xcodeproj
matrix:
  include:
    - xcode_scheme: FeathersSwiftSocketIO-macOS
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION=build
        - XCODE_DESTINATION="arch=x86_64"
    - xcode_scheme: FeathersSwiftSocketIO-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
    - xcode_scheme: FeathersSwiftSocketIO-tvOS
      env:
        - XCODE_SDK=appletvsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
    - script:
        - carthage build --no-skip-current --platform mac
      env:
        - JOB=CARTHAGE-macOS
    - script:
        - carthage build --no-skip-current --platform iOS
      env:
        - JOB=CARTHAGE-iOS
    - script:
        - carthage build --no-skip-current --platform tvOS
      env:
        - JOB=CARTHAGE-tvOS
    - script:
      - gem install cocoapods
      - pod repo update --silent
      - travis_wait 30 pod lib lint FeathersSwiftSocketIO.podspec
      env:
        - JOB=PODSPEC
