language: objective-c
osx_image: xcode8.3

cache:
  - cocoapods
  - directories:
    - Carthage

before_install: true
install:
  - rvm get stable || true
  - brew update || true
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods
  - pod repo update
before_script:
  - pod install
  - chmod +x ./script/build
script:
  - script/build
xcode_workspace: FeathersSwiftSocketIO.xcworkspace
matrix:
  include:
    - xcode_scheme: FeathersSwiftSocketIO-macOS
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION=build
        - XCODE_DESTINATION="arch=x86_64"
    - xcode_scheme: FeathersSwiftSocketIO-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
    - xcode_scheme: FeathersSwiftSocketIO-tvOS
      env:
        - XCODE_SDK=appletvsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
    - xcode_scheme: FeathersSwiftSocketIO-watchOS
      env:
        - XCODE_SDK=watchsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=watchOS Simulator,name=Apple Watch - 38mm,OS=3.2"
    - script: carthage build --no-skip-current --platform mac
      before_script:
        - pod install
        - carthage checkout || true
      env:
        - JOB=CARTHAGE-macOS
    - script: carthage build --no-skip-current --platform iOS
      before_script:
        - pod install
        - carthage checkout || true
      env:
        - JOB=CARTHAGE-iOS
    - script: carthage build --no-skip-current --platform tvOS
      before_script:
        - pod install
        - carthage checkout || true
      env:
        - JOB=CARTHAGE-tvOS
    - script: carthage build --no-skip-current --platform watchOS
      before_script:
        - pod install
        - carthage checkout || true
      env:
        - JOB=CARTHAGE-watchOS
    - script:
      - travis_wait 30 pod lib lint FeathersSwiftSocketIO.podspec
      env:
        - JOB=PODSPEC
